apiVersion: v1
kind: Service
metadata:
  name: workshop-docs
  labels:
    app: workshop-docs
    workshop: low-latency
spec:
  selector:
    app: workshop-docs
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP

