apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: workshop-USER_NAME

resources:
  - ../../base

commonLabels:
  user: USER_NAME

patches:
  - path: patches/buildconfig-patch.yaml
  - path: patches/route-patch.yaml

