apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: workshop-docs
spec:
  strategy:
    dockerStrategy:
      buildArgs:
        - name: USER_NAME
          value: "USER_NAME"
        - name: SNO_GUID
          value: "workshop-USER_NAME"
        - name: SNO_API_URL
          value: "https://api.workshop-USER_NAME.SUBDOMAIN_SUFFIX:6443"
        - name: SNO_CONSOLE_URL
          value: "https://console-openshift-console.apps.workshop-USER_NAME.SUBDOMAIN_SUFFIX"
        - name: BASTION_HOST
          value: "bastion.workshop-USER_NAME.SUBDOMAIN_SUFFIX"
        - name: SUBDOMAIN_SUFFIX
          value: ".SUBDOMAIN_SUFFIX"

