apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Patch HyperConverged to disable software emulation for bare-metal instances
# This ensures native KVM is used (optimal performance) for bare-metal instances
patches:
  - path: patch-hco-disable-emulation.yaml
    target:
      kind: HyperConverged
      name: kubevirt-hyperconverged
